name: easify_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  analyzer: ^0.39.11
  analyzer_plugin: ^0.2.1
  json_serializable: ^3.2.3
  path_provider: ^1.5.1
  uuid: ^2.0.4
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.7
  font_awesome_flutter: ^8.2.0
  moor_flutter: ^3.1.0
  connectivity: ^0.4.6+2
  dartz: ^0.8.6
  equatable: ^0.4.0
  toast: ^0.1.5
  simple_animations: ^1.3.3
  url_launcher: ^5.4.1
  rxdart: ^0.23.1
  provider: ^3.0.0+1

  easify_chat_network:
    git:
      url: https://github.com/vipontes/easify_chat_network.git
      ref: master

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  moor_generator: ^3.3.1
  mobx_codegen: ^1.0.3
  build_runner: ^1.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lang/pt_BR.json
    - lang/en_US.json
    - assets/img/
    - assets/font/

  fonts:
    - family: OpenSans-Bold
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
